name: Push to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to AWS on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Cloud 1
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Install Node.js 22.9.0 and deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 22.9.0
            nvm use 22.9.0

            sudo apt-get -y update
            sudo apt-get -y install nginx
            cd /home
            sudo rm -rf /var/www/*
            sudo mv -f * /var/www
            cd /var/www/
            sudo chown -R root:ubuntu /var/www
            sudo chmod -R 775 /var/www
            npm ci
            npm i -g pm2
            sudo rm /etc/nginx/sites-available/default
            sudo mv -f /var/www/default /etc/nginx/sites-available/
            npx prisma migrate deploy
            pm2 init simple
            pm2 start /var/www/pm2.json

            sudo ufw allow 'Nginx HTTP'
            sudo systemctl start nginx
            sudo systemctl enable nginx
            pm2 reload all --update-env
